import matplotlib.pyplot as plt
import pandas as pd
import  numpy as np
df=pd.read_csv("ceny.csv",sep=";")
print(df)
df["Wartosc"]=df["Wartosc"].str.replace(",",".")
df["Wartosc"]=df["Wartosc"].astype({"Wartosc":"float"})
dane1=df[df["Rodzaje produktów"]=="pstrąg świeży niepatroszony - za 1 kg"]["Wartosc"].mean()
dane2=df[df["Rodzaje produktów"]=="filety z morszczuka mrożone - za 1kg"]["Wartosc"].mean()
dane3=df[df["Rodzaje produktów"]=="śledź solony, niepatroszony - za 1kg"]["Wartosc"].mean()
print(dane1)
print(dane2)
print(dane3)
dane1=df[df["Rodzaje produktów"]=="pstrąg świeży niepatroszony - za 1 kg"].groupby(["Rok"])["Wartosc"].sum()
dane2=df[df["Rodzaje produktów"]=="filety z morszczuka mrożone - za 1kg"].groupby(["Rok"])["Wartosc"].sum()
dane3=df[df["Rodzaje produktów"]=="śledź solony, niepatroszony - za 1kg"].groupby(["Rok"])["Wartosc"].sum()
rok=df["Rok"].drop_duplicates()
plt.bar(rok,dane1,width=0.25,label="pstrąg świeży niepatroszony - za 1 kg")
plt.bar(rok-0.25,dane2,width=0.25,label="filety z morszczuka mrożone - za 1kg")
plt.bar(rok+0.25,dane3,width=0.25,label="śledź solony, niepatroszony - za 1kg")
plt.legend()
plt.xlabel("rok")
plt.ylabel("Wartość")
plt.title("ceny wartość produktów")
plt.savefig("zad2.png")
plt.show()
