import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
df=pd.read_csv("wynagrodzenia.csv",sep="#",header=None).T
df[2]=df[2].str.replace(",",".")
df=df.drop([0])
df[2]=df[2].astype({2:"float"})
df[1]=df[1].astype({1:"int"})
print(df)
dane1=df[df[0]=="POLSKA"].groupby([1])[2].mean()
dane2=df[df[0]=="DOLNOŚLĄSKIE"].groupby([1])[2].sum()
dane3=df[df[0]=="KUJAWSKO-POMORSKIE"].groupby([1])[2].sum()
dane4=df[df[0]=="LUBELSKIE"].groupby([1])[2].sum()
dane5=df[df[0]=="LUBUSKIE"].groupby([1])[2].sum()
dane6=df[df[0]=="ŁÓDZKIE"].groupby([1])[2].sum()
dane7=df[df[0]=="MAŁOPOLSKIE"].groupby([1])[2].sum()
dane8=df[df[0]=="OPOLSKIE"].groupby([1])[2].sum()
dane9=df[df[0]=="PODKARPACKIE"].groupby([1])[2].sum()
dane10=df[df[0]=="PODLASKIE"].groupby([1])[2].sum()
dane11=df[df[0]=="POMORSKIE"].groupby([1])[2].sum()
dane12=df[df[0]=="ŚLĄSKIE"].groupby([1])[2].sum()
dane13=df[df[0]=="ŚWIĘTOKRZYSKIE"].groupby([1])[2].sum()
dane14=df[df[0]=="WARMIŃSKO-MAZURSKIE"].groupby([1])[2].sum()
dane15=df[df[0]=="WIELKOPOLSKIE"].groupby([1])[2].sum()
dane16=df[df[0]=="ZACHODNIOPOMORSKIE"].groupby([1])[2].sum()
rok=df[1].drop_duplicates()
plt.bar(rok,dane1,width=0.05,label="POLSKA")
plt.bar(rok+0.05,dane2,width=0.05,label="DOLNOŚLĄSKIE")
plt.bar(rok+0.10,dane3,width=0.05,label="KUJAWSKO")
plt.bar(rok+0.15,dane4,width=0.05,label="LUBELSKIE")
plt.bar(rok+0.20,dane5,width=0.05,label="LUBUSKIE")
plt.bar(rok+0.25,dane6,width=0.05,label="ŁÓDZKIE")
plt.bar(rok+0.30,dane7,width=0.05,label="MAŁOPOLSKIE")
plt.bar(rok+0.35,dane8,width=0.05,label="OPOLSKIE")
plt.bar(rok+0.40,dane9,width=0.05,label="PODKARPACKIE")
plt.bar(rok+0.45,dane10,width=0.05,label="PODLASKIE")
plt.bar(rok+0.50,dane11,width=0.05,label="POMORSKIE")
plt.bar(rok+0.55,dane12,width=0.05,label="ŚLĄSKIE")
plt.bar(rok+0.60,dane13,width=0.05,label="ŚWIĘTOKRZYSKIE")
plt.bar(rok+0.65,dane14,width=0.05,label="WARMIŃSKO-MAZURSKIE")
plt.bar(rok+0.70,dane15,width=0.05,label="WIELKOPOLSKIE")
plt.bar(rok+0.75,dane16,width=0.05,label="ZACHODNIOPOMORSKIE")
plt.legend()
plt.ylabel("Rok")
plt.xlabel("Wartośc")
plt.savefig("zad3.pdf")
plt.show()





