---
title: "Egzamin (pierwszy termin) - Wizualizacja danych - Zestaw 32"
lang: pl
output:
  word_document: default
  pdf_document: default
---

*Zadanie 1 i 2 po 15 pkt. Zadanie 3 - 20 pkt. *

*Punktacja: 46-50 pkt - bdb(5,0); 41-45 pkt - db+(4,5); 36-40 pkt - db(4,0); 31-35 pkt - dst+(3,5); 26-30 pkt - dst(3,0); 0-25 pkt - ndst (2,0).*  

Zad.1. Odwzoruj wykres znajdujący się w pliku o nazwie w32.png. Odcienie kolorów mogą się różnić, jednak główne barwy muszą być zachowane. Zapisz wykres w formacie pdf za pomocą kodu. 

Zad.2. W jednym pliku wykonaj poniższe czynności:

* załaduj dane z pliku sprzedaz32.xlsx jako ramkę danych (Data Frame),
* wyświetl na konsoli sumę z poszczególnych lat 

produkt 1 - suma ze wszystkich lat

produkt 2 - suma ze wszystkich lat

produkt 3 - suma ze wszystkich lat

* stwórz wykres słupkowy pionowy (może być pogrupowany) prezentujący dane zawarte w ramce danych
* umieść swój numer indeksu w pawym górnym rogu wykresu (wystarczy na jednym)

Wykres powinien być estetyczny i podpisany. Im więcej - tym lepiej.

Zapisz wykres w formacie jpg za pomocą kodu.

Zad.3. W jednym pliku wykonaj poniższe czynności:

* załaduj dane z pliku cechy32.csv,
* usuń wiersze z brakami
* podziel wartości obu cech na koszyki od 100 do 200 z krokiem 20
* stwórz wykres kołowy prezentujący dane zawarte w pliku (mogą być dwa wykresy kołowe)
* Wykres powinien być estetyczny i podpisany. Im więcej - tym lepiej.

Zapisz wykres w formacie png za pomocą kodu.